version: '3.8'

services:
  api:
    container_name: grpc-todo-service
    image: grpc-todo-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/grpc_todo_service
      - /usr/src/grpc_todo_service/node_modules
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      NODE_ENV: dev
      COMPOSE_PROJECT_NAME: grpc
      DATABASE_URL: "mysql://root:password@mysql:3306/todo_service?schema=public"
      GRPC_CONNECTION_URL: 0.0.0.0:3001
    ports:
      - '3001:3001'
      - '9229:9229'
    networks:
      - dev-network
  
  mysql:
    image: mysql/mysql-server:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_service
    networks:
      - dev-network

networks:
  dev-network: {}